#!/bin/bash
# ╔══════════════════════════════════════════════════════╗
# ║  SKYWATCH — Termux All-in-One Launcher               ║
# ║  Calistir: bash skywatch.sh                          ║
# ╚══════════════════════════════════════════════════════╝

G='\033[0;32m'; C='\033[0;36m'; Y='\033[1;33m'; R='\033[0;31m'; N='\033[0m'; B='\033[1m'

clear
echo -e "${G}${B}"
echo "  ███████╗██╗  ██╗██╗   ██╗██╗    ██╗ █████╗ ████████╗ ██████╗██╗  ██╗"
echo "  ██╔════╝██║ ██╔╝╚██╗ ██╔╝██║    ██║██╔══██╗╚══██╔══╝██╔════╝██║  ██║"
echo "  ███████╗█████╔╝  ╚████╔╝ ██║ █╗ ██║███████║   ██║   ██║     ███████║"
echo "  ╚════██║██╔═██╗   ╚██╔╝  ██║███╗██║██╔══██║   ██║   ██║     ██╔══██║"
echo "  ███████║██║  ██╗   ██║   ╚███╔███╔╝██║  ██║   ██║   ╚██████╗██║  ██║"
echo "  ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚══╝╚══╝ ╚═╝  ╚═╝   ╚═╝    ╚═════╝╚═╝  ╚═╝"
echo -e "${N}"

# IP ve Port Ayarlari
PORT=$((RANDOM % 1000 + 8000))
IP_ADDR=$(ifconfig | grep -Et 'inet [0-9]' | grep -v '127.0.0.1' | awk '{print $2}' | head -n 1)
HTML_DIR="$HOME/skywatch_web"
mkdir -p "$HTML_DIR"
HTML="$HTML_DIR/index.html"

PY=$(command -v python3 || command -v python)

echo -e "  ${C}Sunucu Hazirlaniyor: ${G}http://${IP_ADDR}:${PORT}${N}"

$PY << 'PYEOF'
import os
HTML = os.path.expanduser("~/skywatch_web/index.html")

page = (
"<!DOCTYPE html>\n"
"<html lang='tr'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"<title>SKYWATCH</title>\n"
"<link href='https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.css' rel='stylesheet'>\n"
"<script src='https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.js'></script>\n"
"<link href='https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Orbitron:wght@400;700;900&display=swap' rel='stylesheet'>\n"
"<style>\n"
":root{--g:#00ff88;--c:#00e5ff;--o:#ff6b35;--d:#020810;--p:rgba(2,15,25,0.92);--b:rgba(0,255,136,0.25);--t:#a8ffd4}\n"
"*{margin:0;padding:0;box-sizing:border-box}\n"
"body{background:var(--d);color:var(--t);font-family:'Share Tech Mono',monospace;overflow:hidden;height:100vh;width:100vw}\n"
"body::after{content:'';position:fixed;inset:0;background:repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,255,136,.015) 2px,rgba(0,255,136,.015) 4px);pointer-events:none;z-index:9999}\n"
"#map{position:absolute;top:0;left:0;width:100%;height:100%}\n"
".topbar{position:fixed;top:0;left:0;right:0;height:54px;background:var(--p);border-bottom:1px solid var(--b);display:flex;align-items:center;padding:0 16px;gap:14px;z-index:100;backdrop-filter:blur(12px)}\n"
".logo{font-family:'Orbitron',sans-serif;font-weight:900;font-size:17px;color:var(--g);letter-spacing:4px;text-shadow:0 0 20px rgba(0,255,136,.6);white-space:nowrap}\n"
".stats{display:flex;gap:14px;flex:1;overflow:hidden}\n"
".sc{display:flex;align-items:center;gap:6px;font-size:11px;color:rgba(168,255,212,.65);white-space:nowrap}\n"
".sc .v{color:var(--c);font-size:13px}\n"
".dot{width:7px;height:7px;border-radius:50%;background:var(--g);box-shadow:0 0 8px var(--g);animation:pulse 1.5s infinite}\n"
".dot.L{background:var(--o);box-shadow:0 0 8px var(--o)}\n"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}\n"
".tr{display:flex;align-items:center;gap:7px;margin-left:auto}\n"
".clk{font-size:12px;color:var(--c);letter-spacing:2px}\n"
".btn{background:transparent;border:1px solid var(--b);color:var(--g);font-family:'Share Tech Mono',monospace;font-size:10px;padding:5px 9px;cursor:pointer;letter-spacing:1px;transition:all .2s;white-space:nowrap}\n"
".btn:hover,.btn.A{background:rgba(0,255,136,.1);border-color:var(--g)}\n"
".lp{position:fixed;top:54px;left:0;bottom:0;width:255px;background:var(--p);border-right:1px solid var(--b);backdrop-filter:blur(12px);z-index:100;display:flex;flex-direction:column;transition:transform .3s}\n"
".lp.hide{transform:translateX(-255px)}\n"
".ph{padding:11px 14px;border-bottom:1px solid var(--b);font-family:'Orbitron',sans-serif;font-size:10px;letter-spacing:3px;color:var(--g);display:flex;justify-content:space-between}\n"
".fl{flex:1;overflow-y:auto}\n"
".fi{padding:9px 14px;border-bottom:1px solid rgba(0,255,136,.07);cursor:pointer}\n"
".fi:hover,.fi.sel{background:rgba(0,255,136,.08)}\n"
".fc{font-family:'Orbitron',sans-serif;font-size:12px;color:var(--c);letter-spacing:1px}\n"
".fd{font-size:10px;color:rgba(168,255,212,.5);display:flex;gap:10px;margin-top:3px}\n"
".ptg{position:fixed;top:68px;left:255px;width:18px;height:36px;background:var(--p);border:1px solid var(--b);border-left:none;z-index:101;display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:11px;color:var(--g);transition:left .3s}\n"
".ptg.hide{left:0}\n"
".ip{position:fixed;bottom:18px;right:18px;width:285px;background:var(--p);border:1px solid var(--b);backdrop-filter:blur(16px);z-index:100;display:none}\n"
".ip.vis{display:block}\n"
".ih{padding:10px 14px;background:rgba(0,255,136,.07);border-bottom:1px solid var(--b);font-family:'Orbitron',sans-serif;font-size:13px;color:var(--c);letter-spacing:2px;display:flex;justify-content:space-between;align-items:center}\n"
".ix{cursor:pointer;color:rgba(168,255,212,.45);font-size:17px}\n"
".ib{padding:12px 14px;display:grid;grid-template-columns:1fr 1fr;gap:10px}\n"
".ifd{display:flex;flex-direction:column;gap:3px}\n"
".il{font-size:9px;color:rgba(168,255,212,.4);letter-spacing:2px;text-transform:uppercase}\n"
".iv{font-size:13px;color:var(--g);font-family:'Orbitron',sans-serif}\n"
".rc{position:fixed;bottom:18px;left:18px;z-index:100;background:var(--p);border:1px solid var(--b);padding:8px}\n"
".hm{position:fixed;top:50%;right:18px;transform:translateY(-50%);z-index:100;display:flex;flex-direction:column;gap:8px}\n"
".mt{background:var(--p);border:1px solid var(--b);padding:9px 11px;width:82px}\n"
".mla{font-size:8px;color:rgba(168,255,212,.4);text-transform:uppercase}\n"
".mv{font-family:'Orbitron',sans-serif;font-size:17px;color:var(--c);line-height:1}\n"
"#ld{position:fixed;inset:0;background:var(--d);z-index:200;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px}\n"
".ll{font-family:'Orbitron',sans-serif;font-size:34px;font-weight:900;color:var(--g);letter-spacing:8px;animation:glow 2s infinite}\n"
"@keyframes glow{0%,100%{text-shadow:0 0 20px rgba(0,255,136,.4)}50%{text-shadow:0 0 60px rgba(0,255,136,.9)}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<div id='ld'><div class='ll'>SKYWATCH</div><div style='font-size:11px;color:rgba(168,255,212,.4)'>SISTEM YUKLENIYOR...</div></div>\n"
"\n"
"<div class='topbar'>\n"
"  <div class='logo'>SKYWATCH</div>\n"
"  <div class='stats'>\n"
"    <div class='sc'><div class='dot' id='sd'></div><span id='st'>ONLINE</span></div>\n"
"    <div class='sc'>UCAK: <span class='v' id='pc'>0</span></div>\n"
"  </div>\n"
"  <div class='tr'><div class='clk' id='clk'>00:00:00</div><button class='btn' onclick='location.reload()'>YENILE</button></div>\n"
"</div>\n"
"\n"
"<div class='ptg' id='ptg' onclick='togglePanel()'>&#9664;</div>\n"
"<div class='lp' id='lp'>\n"
"  <div class='ph'><span>UCUS LISTESI</span><span id='pct'>0</span></div>\n"
"  <div class='fl' id='fl'></div>\n"
"</div>\n"
"\n"
"<div id='map'></div>\n"
"\n"
"<div class='ip' id='ip'>\n"
"  <div class='ih'><span id='ics'>---</span><span class='ix' onclick='closeInfo()'>&#215;</span></div>\n"
"  <div class='ib'>\n"
"    <div class='ifd'><div class='il'>HAVAYOLU</div><div class='iv' id='iop'>---</div></div>\n"
"    <div class='ifd'><div class='il'>ULKE</div><div class='iv' id='ico'>---</div></div>\n"
"    <div class='ifd'><div class='il'>YUKSEKLIK</div><div class='iv' id='ial'>---</div></div>\n"
"    <div class='ifd'><div class='il'>TREND</div><div class='iv' id='itr'>---</div></div>\n"
"    <div class='ifd'><div class='il'>HIZ</div><div class='iv' id='isp'>---</div></div>\n"
"    <div class='ifd'><div class='il'>SQUAWK</div><div class='iv' id='isq'>---</div></div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class='hm' id='hm'>\n"
"  <div class='mt'><div class='mla'>YUKSEK</div><div class='mv' id='ha'>---</div></div>\n"
"  <div class='mt'><div class='mla'>HIZ</div><div class='mv' id='hs'>---</div></div>\n"
"</div>\n"
"\n"
"<script>\n"
"var map=null, mbToken='', flights=[], selIcao=null, markers={};\n"
"const AIRLINES = {'THY':'TURKISH AIR','PGT':'PEGASUS','DLH':'LUFTHANSA','BAW':'BRITISH AW','AFR':'AIR FRANCE'};\n"
"\n"
"if(!mbToken) { mbToken = localStorage.getItem('mbt') || prompt('Mapbox Token:'); if(mbToken) localStorage.setItem('mbt', mbToken); }\n"
"\n"
"mapboxgl.accessToken = mbToken;\n"
"map = new mapboxgl.Map({container:'map', style:'mapbox://styles/mapbox/satellite-v9', center:[35,39], zoom:5});\n"
"\n"
"map.on('load', function(){\n"
"  document.getElementById('ld').style.display='none';\n"
"  updateData();\n"
"  setInterval(updateData, 25000);\n"
"  setInterval(function(){document.getElementById('clk').textContent=new Date().toTimeString().slice(0,8);},1000);\n"
"  // Rota Kaynagi\n"
"  map.addSource('route', {type:'geojson', data:{type:'Feature', geometry:{type:'LineString', coordinates:[]}}});\n"
"  map.addLayer({id:'route-line', type:'line', source:'route', paint:{'line-color':'#00ff88', 'line-width':2}});\n"
"});\n"
"\n"
"function togglePanel(){\n"
"  var p=document.getElementById('lp'),t=document.getElementById('ptg');\n"
"  p.classList.toggle('hide'); t.classList.toggle('hide');\n"
"  t.innerHTML = p.classList.contains('hide') ? '&#9654;' : '&#9664;';\n"
"}\n"
"\n"
"async function updateData(){\n"
"  var r=await fetch('https://opensky-network.org/api/states/all?lamin
