#!/bin/bash
# ╔══════════════════════════════════════════════════════╗
# ║  SKYWATCH — Termux All-in-One Launcher               ║
# ║  Calistir: bash skywatch.sh                          ║
# ╚══════════════════════════════════════════════════════╝

G='\033[0;32m'; C='\033[0;36m'; Y='\033[1;33m'; R='\033[0;31m'; N='\033[0m'; B='\033[1m'

clear
echo ""
echo -e "${G}${B}"
echo "  ███████╗██╗  ██╗██╗   ██╗██╗    ██╗ █████╗ ████████╗ ██████╗██╗  ██╗"
echo "  ██╔════╝██║ ██╔╝╚██╗ ██╔╝██║    ██║██╔══██╗╚══██╔══╝██╔════╝██║  ██║"
echo "  ███████╗█████╔╝  ╚████╔╝ ██║ █╗ ██║███████║   ██║   ██║     ███████║"
echo "  ╚════██║██╔═██╗   ╚██╔╝  ██║███╗██║██╔══██║   ██║   ██║     ██╔══██║"
echo "  ███████║██║  ██╗   ██║   ╚███╔███╔╝██║  ██║   ██║   ╚██████╗██║  ██║"
echo "  ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚══╝╚══╝ ╚═╝  ╚═╝    ╚═╝    ╚═════╝╚═╝  ╚═╝"
echo -e "${N}"
echo -e "  ${C}Canli Ucak Takip — OpenSky + Mapbox Uydu${N}"
echo "  ───────────────────────────────────────────"
echo ""

# Python kontrol
if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null; then
  echo -e "  ${Y}Python yukleniyor...${N}"
  pkg install python -y
fi

PY=$(command -v python3 || command -v python)
TMPD="${TMPDIR:-/tmp}"
HTML="$TMPD/skywatch_index.html"

echo -e "  ${C}HTML olusturuluyor...${N}"

# HTML dosyasini Python ile yaz (heredoc tirnak sorununu atar)
$PY << 'PYEOF'
import os, sys, json

TMPD = os.environ.get("TMPDIR", "/tmp")
HTML = os.path.join(TMPD, "skywatch_index.html")

page = (
"<!DOCTYPE html>\n"
"<html lang='tr'>\n"
"<head>\n"
"<meta charset='UTF-8'>\n"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>\n"
"<title>SKYWATCH</title>\n"
"<link href='https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.css' rel='stylesheet'>\n"
"<script src='https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.js'></script>\n"
"<link href='https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Orbitron:wght@400;700;900&display=swap' rel='stylesheet'>\n"
"<style>\n"
":root{--g:#00ff88;--c:#00e5ff;--o:#ff6b35;--d:#020810;--p:rgba(2,15,25,0.92);--b:rgba(0,255,136,0.25);--t:#a8ffd4}\n"
"*{margin:0;padding:0;box-sizing:border-box}\n"
"body{background:var(--d);color:var(--t);font-family:'Share Tech Mono',monospace;overflow:hidden;height:100vh;width:100vw}\n"
"body::after{content:'';position:fixed;inset:0;background:repeating-linear-gradient(0deg,transparent,transparent 2px,rgba(0,255,136,.015) 2px,rgba(0,255,136,.015) 4px);pointer-events:none;z-index:9999}\n"
"#map{position:absolute;top:0;left:0;width:100%;height:100%}\n"
".topbar{position:fixed;top:0;left:0;right:0;height:54px;background:var(--p);border-bottom:1px solid var(--b);display:flex;align-items:center;padding:0 16px;gap:14px;z-index:100;backdrop-filter:blur(12px)}\n"
".logo{font-family:'Orbitron',sans-serif;font-weight:900;font-size:17px;color:var(--g);letter-spacing:4px;text-shadow:0 0 20px rgba(0,255,136,.6);white-space:nowrap}\n"
".stats{display:flex;gap:14px;flex:1;overflow:hidden}\n"
".sc{display:flex;align-items:center;gap:6px;font-size:11px;color:rgba(168,255,212,.65);white-space:nowrap}\n"
".sc .v{color:var(--c);font-size:13px}\n"
".dot{width:7px;height:7px;border-radius:50%;background:var(--g);box-shadow:0 0 8px var(--g);animation:pulse 1.5s infinite}\n"
".dot.L{background:var(--o);box-shadow:0 0 8px var(--o)}\n"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.3}}\n"
".tr{display:flex;align-items:center;gap:7px;margin-left:auto}\n"
".clk{font-size:12px;color:var(--c);letter-spacing:2px}\n"
".btn{background:transparent;border:1px solid var(--b);color:var(--g);font-family:'Share Tech Mono',monospace;font-size:10px;padding:5px 9px;cursor:pointer;letter-spacing:1px;transition:all .2s;white-space:nowrap}\n"
".btn:hover,.btn.A{background:rgba(0,255,136,.1);border-color:var(--g);box-shadow:0 0 10px rgba(0,255,136,.2)}\n"
".lp{position:fixed;top:54px;left:0;bottom:0;width:255px;background:var(--p);border-right:1px solid var(--b);backdrop-filter:blur(12px);z-index:100;display:flex;flex-direction:column;transition:transform .3s}\n"
".lp.hide{transform:translateX(-255px)}\n"
".ph{padding:11px 14px;border-bottom:1px solid var(--b);font-family:'Orbitron',sans-serif;font-size:10px;letter-spacing:3px;color:var(--g);display:flex;justify-content:space-between}\n"
".fl{flex:1;overflow-y:auto;scrollbar-width:thin;scrollbar-color:var(--b) transparent}\n"
".fi{padding:9px 14px;border-bottom:1px solid rgba(0,255,136,.07);cursor:pointer;transition:background .15s}\n"
".fi:hover,.fi.sel{background:rgba(0,255,136,.08)}\n"
".fc{font-family:'Orbitron',sans-serif;font-size:12px;color:var(--c);letter-spacing:1px}\n"
".fd{font-size:10px;color:rgba(168,255,212,.5);display:flex;gap:10px;margin-top:3px}\n"
".ptg{position:fixed;top:68px;left:255px;width:18px;height:36px;background:var(--p);border:1px solid var(--b);border-left:none;z-index:101;display:flex;align-items:center;justify-content:center;cursor:pointer;font-size:11px;color:var(--g);transition:left .3s}\n"
".ptg:hover{background:rgba(0,255,136,.1)}\n"
".ptg.hide{left:0}\n"
".ip{position:fixed;bottom:18px;right:18px;width:285px;background:var(--p);border:1px solid var(--b);backdrop-filter:blur(16px);z-index:100;display:none}\n"
".ip.vis{display:block}\n"
".ih{padding:10px 14px;background:rgba(0,255,136,.07);border-bottom:1px solid var(--b);font-family:'Orbitron',sans-serif;font-size:13px;color:var(--c);letter-spacing:2px;display:flex;justify-content:space-between;align-items:center}\n"
".ix{cursor:pointer;color:rgba(168,255,212,.45);font-size:17px}\n"
".ix:hover{color:var(--o)}\n"
".ib{padding:12px 14px;display:grid;grid-template-columns:1fr 1fr;gap:10px}\n"
".ifd{display:flex;flex-direction:column;gap:3px}\n"
".il{font-size:9px;color:rgba(168,255,212,.4);letter-spacing:2px;text-transform:uppercase}\n"
".iv{font-size:13px;color:var(--g);font-family:'Orbitron',sans-serif}\n"
".iv.h{color:var(--c)}\n"
".rc{position:fixed;bottom:18px;left:18px;z-index:100;background:var(--p);border:1px solid var(--b);padding:8px;backdrop-filter:blur(12px)}\n"
".rl{font-size:9px;color:rgba(168,255,212,.4);letter-spacing:2px;margin-bottom:5px;text-transform:uppercase}\n"
".hm{position:fixed;top:50%;right:18px;transform:translateY(-50%);z-index:100;display:flex;flex-direction:column;gap:8px;opacity:0;transition:opacity .3s;pointer-events:none}\n"
".hm.vis{opacity:1}\n"
".mt{background:var(--p);border:1px solid var(--b);padding:9px 11px;width:82px;backdrop-filter:blur(12px)}\n"
".mla{font-size:8px;color:rgba(168,255,212,.4);letter-spacing:2px;text-transform:uppercase;margin-bottom:3px}\n"
".mv{font-family:'Orbitron',sans-serif;font-size:17px;color:var(--c);line-height:1}\n"
".mu{font-size:8px;color:rgba(168,255,212,.45);margin-top:2px}\n"
".ntf{position:fixed;top:68px;right:18px;background:var(--p);border:1px solid var(--b);padding:9px 14px;font-size:11px;color:var(--c);z-index:150;transform:translateX(120%);transition:transform .3s;letter-spacing:1px}\n"
".ntf.sh{transform:translateX(0)}\n"
".ntf.er{color:var(--o);border-color:rgba(255,107,53,.4)}\n"
".rb{position:fixed;bottom:0;left:0;right:0;height:2px;background:rgba(0,255,136,.07);z-index:100}\n"
".rp{height:100%;background:var(--g);box-shadow:0 0 8px var(--g);width:100%}\n"
".mapboxgl-ctrl-bottom-left,.mapboxgl-ctrl-bottom-right{display:none!important}\n"
".mapboxgl-popup-content{background:var(--p)!important;border:1px solid var(--b)!important;color:var(--t)!important;font-family:'Share Tech Mono',monospace!important;font-size:11px!important;padding:9px 13px!important;border-radius:0!important}\n"
".mapboxgl-popup-tip{display:none!important}\n"
"#ld{position:fixed;inset:0;background:var(--d);z-index:200;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:18px;transition:opacity .5s}\n"
"#ld.hide{opacity:0;pointer-events:none}\n"
".ll{font-family:'Orbitron',sans-serif;font-size:34px;font-weight:900;color:var(--g);letter-spacing:8px;animation:glow 2s infinite}\n"
"@keyframes glow{0%,100%{text-shadow:0 0 20px rgba(0,255,136,.4)}50%{text-shadow:0 0 60px rgba(0,255,136,.9)}}\n"
".lbw{width:280px;height:2px;background:rgba(0,255,136,.12);overflow:hidden}\n"
".lb{height:100%;background:var(--g);box-shadow:0 0 10px var(--g);width:0%;transition:width .4s}\n"
".lt{font-size:11px;color:rgba(168,255,212,.45);letter-spacing:3px;text-transform:uppercase}\n"
"#tm{position:fixed;inset:0;background:rgba(2,8,16,.96);z-index:300;display:flex;align-items:center;justify-content:center}\n"
"#tm.hide{display:none}\n"
".mb{background:var(--p);border:1px solid var(--b);padding:28px;width:440px;max-width:95vw}\n"
".mt2{font-family:'Orbitron',sans-serif;font-size:15px;color:var(--c);letter-spacing:3px;margin-bottom:8px}\n"
".md{font-size:11px;color:rgba(168,255,212,.55);line-height:1.75;margin-bottom:18px}\n"
".md a{color:var(--c);text-decoration:none}\n"
".ti{width:100%;background:rgba(0,229,255,.05);border:1px solid var(--b);color:var(--c);font-family:'Share Tech Mono',monospace;font-size:12px;padding:10px 13px;outline:none;margin-bottom:12px}\n"
".ti:focus{border-color:var(--c)}\n"
".ma{display:flex;gap:10px}\n"
".bp{flex:1;background:rgba(0,255,136,.1);border:1px solid var(--g);color:var(--g);font-family:'Share Tech Mono',monospace;font-size:11px;padding:10px;cursor:pointer;letter-spacing:2px}\n"
".bp:hover{background:rgba(0,255,136,.2)}\n"
".bd{background:rgba(0,229,255,.07);border:1px solid rgba(0,229,255,.28);color:var(--c);font-family:'Share Tech Mono',monospace;font-size:11px;padding:10px;cursor:pointer;letter-spacing:2px}\n"
".bd:hover{background:rgba(0,229,255,.14)}\n"
".fl::-webkit-scrollbar{width:3px}\n"
".fl::-webkit-scrollbar-thumb{background:var(--b)}\n"
"@media(max-width:600px){.lp{width:220px}.ptg{left:220px}.ptg.hide{left:0}.rc{display:none}.ip{right:8px;bottom:8px;width:calc(100vw - 16px)}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<div id='tm'>\n"
"  <div class='mb'>\n"
"    <div class='mt2'>MAPBOX TOKEN</div>\n"
"    <p class='md'>\n"
"      Uydu haritasi icin ucretsiz Mapbox token gereklidir.<br>\n"
"      <a href='https://account.mapbox.com' target='_blank'>account.mapbox.com</a> adresinden alin.<br><br>\n"
"      Token olmadan <b>Demo Mod</b> ile ucak listesi goruntulenebilir.\n"
"    </p>\n"
"    <input class='ti' id='ti' type='text' placeholder='pk.eyJ1IjoiLi4uIiwiYSI6Ii4uLiJ9...'>\n"
"    <div class='ma'>\n"
"      <button class='bp' onclick='initWithToken()'>BASLAT</button>\n"
"      <button class='bd' onclick='initDemo()'>DEMO MOD</button>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div id='ld'>\n"
"  <div class='ll'>SKYWATCH</div>\n"
"  <div class='lbw'><div class='lb' id='lb'></div></div>\n"
"  <div class='lt' id='lt'>SISTEM BASLATILIYOR...</div>\n"
"</div>\n"
"\n"
"<div class='topbar'>\n"
"  <div class='logo'>SKYWATCH</div>\n"
"  <div class='stats'>\n"
"    <div class='sc'><div class='dot L' id='sd'></div><span id='st'>BAGLANILIYOR</span></div>\n"
"    <div class='sc'>UCAK: <span class='v' id='pc'>0</span></div>\n"
"    <div class='sc'>SON: <span class='v' id='lu'>--:--</span></div>\n"
"  </div>\n"
"  <div class='tr'>\n"
"    <div class='clk' id='clk'>00:00:00</div>\n"
"    <button class='btn' onclick='refreshData()'>&#8635; YENILE</button>\n"
"    <button class='btn A' id='lsb' onclick='setLayer(\"satellite\")'>UYDU</button>\n"
"    <button class='btn' id='ldb' onclick='setLayer(\"dark\")'>KARANLIK</button>\n"
"    <button class='btn' id='lrb' onclick='setLayer(\"street\")'>SOKAK</button>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class='ptg' id='ptg' onclick='togglePanel()'>&#9664;</div>\n