#!/bin/bash

################################################################################
# PEGASUS PROJECT v6.0 - ADVANCED FEATURES & PLUGINS
# Ek özellikler ve entegrasyon modülleri
################################################################################

# Renkler
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
WHITE='\033[1;37m'
NC='\033[0m'

################################################################################
# 1. DÜZELTİLMİŞ SİSTEM TARAMA
################################################################################

advanced_system_scan() {
    local scan_report="/sdcard/pegasus_scan_$(date +%Y%m%d_%H%M%S).txt"
    
    {
        echo "╔════════════════════════════════════════════════════════════════╗"
        echo "║           PEGASUS ADVANCED SYSTEM SCAN REPORT                 ║"
        echo "║           $(date '+%Y-%m-%d %H:%M:%S UTC')                                      ║"
        echo "╚════════════════════════════════════════════════════════════════╝"
        echo ""
        
        # CPU Analizi
        echo "[CPU ANALYSIS]"
        if [ -f /proc/cpuinfo ]; then
            echo "Total Cores: $(grep -c "processor" /proc/cpuinfo)"
            echo "Model: $(grep "model name" /proc/cpuinfo | head -1 | cut -d':' -f2)"
            echo "CPU Speed: $(grep "cpu MHz" /proc/cpuinfo | head -1 | cut -d':' -f2)"
        fi
        echo ""
        
        # Bellek Detayları
        echo "[MEMORY ANALYSIS]"
        if [ -f /proc/meminfo ]; then
            awk '
                /MemTotal/ {printf "Total Memory: %d MB\n", $2/1024}
                /MemFree/ {printf "Free Memory: %d MB\n", $2/1024}
                /MemAvailable/ {printf "Available Memory: %d MB\n", $2/1024}
                /Buffers/ {printf "Buffers: %d MB\n", $2/1024}
                /Cached/ {printf "Cached: %d MB\n", $2/1024}
                /SwapTotal/ {printf "Swap Total: %d MB\n", $2/1024}
                /SwapFree/ {printf "Swap Free: %d MB\n", $2/1024}
            ' /proc/meminfo
        fi
        echo ""
        
        # Disk I/O İstatistikleri
        echo "[DISK I/O STATISTICS]"
        if [ -f /proc/diskstats ]; then
            echo "Disk Activity:"
            head -5 /proc/diskstats | awk '{printf "  %s: reads=%s, writes=%s\n", $3, $4, $8}'
        fi
        echo ""
        
        # Ağ İstatistikleri
        echo "[NETWORK STATISTICS]"
        if [ -f /proc/net/dev ]; then
            echo "Interface Statistics:"
            tail -n +3 /proc/net/dev | awk '{printf "  %s: RX=%s bytes, TX=%s bytes\n", $1, $2, $10}'
        fi
        echo ""
        
        # Sistem Yüklenmesi
        echo "[SYSTEM LOAD AVERAGE]"
        if [ -f /proc/loadavg ]; then
            cat /proc/loadavg | awk '{printf "1 min: %s | 5 min: %s | 15 min: %s\n", $1, $2, $3}'
        fi
        echo ""
        
        # Çalışan Hizmetler
        echo "[RUNNING SERVICES]"
        if command -v ps &> /dev/null; then
            ps aux | tail -10 | awk '{printf "  %s (PID: %d, CPU: %s%%)\n", $11, $2, $3}'
        fi
        echo ""
        
        # Açık Dosya Tanıtıcıları
        echo "[OPEN FILE DESCRIPTORS]"
        if [ -d /proc/self/fd ]; then
            echo "Total FDs: $(ls /proc/self/fd | wc -l)"
        fi
        echo ""
        
        echo "═══════════════════════════════════════════════════════════════"
        echo "Report generated by PEGASUS v6.0 - $(hostname)"
        
    } | tee "$scan_report"
    
    echo -e "${GREEN}✓ Tarama raporu kaydedildi: $scan_report${NC}"
}

################################################################################
# 2. AĞ GÜVENLIK ANALİZİ
################################################################################

network_security_audit() {
    local audit_report="/sdcard/pegasus_security_$(date +%Y%m%d_%H%M%S).txt"
    
    {
        echo "╔════════════════════════════════════════════════════════════════╗"
        echo "║         PEGASUS NETWORK SECURITY AUDIT REPORT                 ║"
        echo "║           $(date '+%Y-%m-%d %H:%M:%S UTC')                                      ║"
        echo "╚════════════════════════════════════════════════════════════════╝"
        echo ""
        
        echo "[FIREWALL STATUS]"
        if command -v iptables &> /dev/null; then
            iptables -L -n | head -20
        else
            echo "iptables not available"
        fi
        echo ""
        
        echo "[LISTENING PORTS]"
        if [ -f /proc/net/tcp ]; then
            echo "TCP Listening Ports:"
            awk '
                NR>1 {
                    if ($4 == "0A") {
                        split($2, a, ":");
                        port = strtonum("0x" a[2]);
                        if (port > 0) printf "  Port: %d (LISTEN)\n", port;
                    }
                }
            ' /proc/net/tcp | sort -u | head -20
        fi
        echo ""
        
        echo "[ESTABLISHED CONNECTIONS]"
        if [ -f /proc/net/tcp ]; then
            count=$(awk 'NR>1 && $4 == "01" {count++} END {print count}' /proc/net/tcp)
            echo "Active Connections: $count"
        fi
        echo ""
        
        echo "[SUSPICIOUS PROCESSES]"
        if command -v ps &> /dev/null; then
            echo "High resource consumers:"
            ps aux --sort=-%cpu | head -6 | tail -5 | awk '{printf "  %s (CPU: %s%%, MEM: %s%%)\n", substr($11,1,30), $3, $4}'
        fi
        echo ""
        
        echo "[SYSTEM SECURITY CHECKS]"
        echo "File Integrity:"
        if [ -f /etc/passwd ]; then
            echo "  /etc/passwd: $(stat /etc/passwd | grep Modify)"
        fi
        if [ -f /etc/shadow ]; then
            echo "  /etc/shadow: $(stat /etc/shadow | grep Modify)"
        fi
        echo ""
        
        echo "═══════════════════════════════════════════════════════════════"
        echo "Security audit generated by PEGASUS v6.0"
        
    } | tee "$audit_report"
    
    echo -e "${GREEN}✓ Güvenlik denetim raporu kaydedildi: $audit_report${NC}"
}

################################################################################
# 3. PERFORMANS BENCHMARKİ
################################################################################

performance_benchmark() {
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║        PEGASUS PERFORMANCE BENCHMARK SUITE                     ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    # CPU Test
    echo -e "${YELLOW}[1/4] CPU Benchmark...${NC}"
    local cpu_result=$(
        local count=0
        for i in {1..100000}; do
            count=$((count + i))
        done
        echo $count
    )
    echo -e "${GREEN}✓ CPU Test Completed: $cpu_result operations${NC}"
    echo ""
    
    # Bellek Test
    echo -e "${YELLOW}[2/4] Memory Benchmark...${NC}"
    local mem_test=$(dd if=/dev/zero bs=1M count=10 2>&1 | tail -1)
    echo -e "${GREEN}✓ Memory Test: $mem_test${NC}"
    echo ""
    
    # Disk Test
    echo -e "${YELLOW}[3/4] Disk I/O Benchmark...${NC}"
    local disk_test=$(dd if=/dev/zero of=/tmp/test_file bs=1M count=5 2>&1 | tail -1)
    rm -f /tmp/test_file
    echo -e "${GREEN}✓ Disk Test: $disk_test${NC}"
    echo ""
    
    # Network Test (eğer ping mevcut ise)
    echo -e "${YELLOW}[4/4] Network Benchmark...${NC}"
    if command -v ping &> /dev/null; then
        local net_result=$(ping -c 1 8.8.8.8 2>/dev/null | grep time= | tail -1)
        echo -e "${GREEN}✓ Network Test: $net_result${NC}"
    else
        echo -e "${YELLOW}⚠ Network test skipped (ping unavailable)${NC}"
    fi
    echo ""
    
    echo -e "${GREEN}Benchmark tamamlandı!${NC}"
}

################################################################################
# 4. OLAY TÜRÜ MONİTÖRÜ
################################################################################

event_type_monitor() {
    local event_log="/sdcard/pegasus_events.log"
    
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║         PEGASUS EVENT TYPE MONITOR                            ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    # Event türlerini kategorize et
    echo "[SYSTEM EVENTS]"
    echo "  • Boot Events: $(grep -c "Boot\|Startup\|Initialize" "$event_log" 2>/dev/null || echo 0)"
    echo "  • Shutdown Events: $(grep -c "Shutdown\|Halt\|Terminate" "$event_log" 2>/dev/null || echo 0)"
    echo "  • Error Events: $(grep -c "ERROR\|Error\|error" "$event_log" 2>/dev/null || echo 0)"
    echo ""
    
    echo "[NETWORK EVENTS]"
    echo "  • Connection Events: $(grep -c "Connection\|Connect" "$event_log" 2>/dev/null || echo 0)"
    echo "  • Disconnection Events: $(grep -c "Disconnect" "$event_log" 2>/dev/null || echo 0)"
    echo "  • Transfer Events: $(grep -c "Transfer\|Send\|Receive" "$event_log" 2>/dev/null || echo 0)"
    echo ""
    
    echo "[PROCESS EVENTS]"
    echo "  • Process Start: $(grep -c "start\|START" "$event_log" 2>/dev/null || echo 0)"
    echo "  • Process End: $(grep -c "end\|END\|exit" "$event_log" 2>/dev/null || echo 0)"
    echo ""
    
    echo -e "${GREEN}Real-time monitoring: $(wc -l < "$event_log" 2>/dev/null || echo 0) entries${NC}"
}

################################################################################
# 5. VERI DIŞA AKTARMA (İLERİ)
################################################################################

advanced_data_export() {
    local export_dir="/sdcard/pegasus_exports"
    mkdir -p "$export_dir"
    
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║         PEGASUS ADVANCED DATA EXPORT                          ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    echo "Export Seçenekleri:"
    echo "1) JSON Format"
    echo "2) CSV Format"
    echo "3) XML Format"
    echo "4) HTML Report"
    echo "5) Compressed Archive"
    echo ""
    
    read -p "Seçim yapınız (1-5): " export_choice
    
    case $export_choice in
        1)
            export_json "$export_dir"
            ;;
        2)
            export_csv "$export_dir"
            ;;
        3)
            export_xml "$export_dir"
            ;;
        4)
            export_html "$export_dir"
            ;;
        5)
            export_archive "$export_dir"
            ;;
        *)
            echo -e "${RED}Geçersiz seçim${NC}"
            ;;
    esac
}

export_json() {
    local dir=$1
    local json_file="$dir/pegasus_export_$(date +%Y%m%d_%H%M%S).json"
    
    cat > "$json_file" << 'EOF'
{
  "metadata": {
    "version": "6.0",
    "build": "zd404",
    "timestamp": "$(date -Iseconds)",
    "hostname": "$(hostname)"
  },
  "system": {
    "cpu": {
      "usage": "$(get_cpu_info)%",
      "cores": "$(grep -c processor /proc/cpuinfo)"
    },
    "memory": {
      "total_mb": "$(awk '/MemTotal/ {print int($2/1024)}' /proc/meminfo)",
      "usage_percent": "$(get_memory_info)%"
    },
    "storage": {
      "usage_percent": "$(get_storage_info)%"
    }
  },
  "network": {
    "active_connections": "$(get_active_connections)",
    "processes": "$(get_process_count)"
  }
}
EOF
    
    echo -e "${GREEN}✓ JSON raporu kaydedildi: $json_file${NC}"
}

export_csv() {
    local dir=$1
    local csv_file="$dir/pegasus_export_$(date +%Y%m%d_%H%M%S).csv"
    
    {
        echo "Timestamp,Metric,Value,Unit"
        echo "$(date),CPU Usage,$(get_cpu_info),%"
        echo "$(date),Memory Usage,$(get_memory_info),%"
        echo "$(date),Storage Usage,$(get_storage_info),%"
        echo "$(date),Active Connections,$(get_active_connections),count"
        echo "$(date),Running Processes,$(get_process_count),count"
    } > "$csv_file"
    
    echo -e "${GREEN}✓ CSV raporu kaydedildi: $csv_file${NC}"
}

export_xml() {
    local dir=$1
    local xml_file="$dir/pegasus_export_$(date +%Y%m%d_%H%M%S).xml"
    
    cat > "$xml_file" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<pegasus>
    <metadata>
        <version>6.0</version>
        <build>zd404</build>
        <timestamp>$(date -Iseconds)</timestamp>
    </metadata>
    <system>
        <cpu>
            <usage>$(get_cpu_info)</usage>
            <unit>%</unit>
        </cpu>
        <memory>
            <usage>$(get_memory_info)</usage>
            <unit>%</unit>
        </memory>
    </system>
</pegasus>
EOF
    
    echo -e "${GREEN}✓ XML raporu kaydedildi: $xml_file${NC}"
}

export_html() {
    local dir=$1
    local html_file="$dir/pegasus_export_$(date +%Y%m%d_%H%M%S).html"
    
    cat > "$html_file" << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>PEGASUS Report</title>
    <style>
        body { background: #0a0e27; color: #00ff41; font-family: monospace; }
        .container { max-width: 1200px; margin: 20px auto; }
        .header { border: 2px solid #00ff41; padding: 10px; margin: 10px 0; }
        .metric { display: inline-block; width: 45%; margin: 10px; padding: 10px; border: 1px solid #00ff41; }
        .progress { width: 100%; background: #1a1a2e; border: 1px solid #00ff41; }
        .bar { background: #00ff41; height: 20px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔴 PEGASUS PROJECT v6.0</h1>
            <p>System Monitoring Report</p>
        </div>
        
        <div class="metric">
            <h3>CPU Usage</h3>
            <div class="progress">
                <div class="bar" style="width: $(get_cpu_info)%"></div>
            </div>
            <p>$(get_cpu_info)%</p>
        </div>
        
        <div class="metric">
            <h3>Memory Usage</h3>
            <div class="progress">
                <div class="bar" style="width: $(get_memory_info)%"></div>
            </div>
            <p>$(get_memory_info)%</p>
        </div>
    </div>
</body>
</html>
EOF
    
    echo -e "${GREEN}✓ HTML raporu kaydedildi: $html_file${NC}"
}

export_archive() {
    local dir=$1
    local archive="$dir/pegasus_backup_$(date +%Y%m%d_%H%M%S).tar.gz"
    
    tar -czf "$archive" \
        /sdcard/pegasus_monitor.log \
        /sdcard/.pegasus_config \
        /sdcard/pegasus_scan*.txt \
        /sdcard/pegasus_security*.txt \
        2>/dev/null
    
    echo -e "${GREEN}✓ Arşiv kaydedildi: $archive${NC}"
}

################################################################################
# 6. UYARI AYARLARI
################################################################################

setup_alerts() {
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║         PEGASUS ALERT CONFIGURATION                           ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    echo "Uyarı Kurallarını Ayarlayın:"
    echo ""
    
    read -p "CPU kullanımı %'si uyarı tetiklemesin (varsayılan 85): " cpu_threshold
    cpu_threshold=${cpu_threshold:-85}
    
    read -p "Bellek kullanımı %'si uyarı tetiklemesin (varsayılan 80): " mem_threshold
    mem_threshold=${mem_threshold:-80}
    
    read -p "Disk kullanımı %'si uyarı tetiklemesin (varsayılan 90): " disk_threshold
    disk_threshold=${disk_threshold:-90}
    
    # Alertları dosyaya kaydet
    cat > /sdcard/.pegasus_alerts << EOF
CPU_THRESHOLD=$cpu_threshold
MEMORY_THRESHOLD=$mem_threshold
DISK_THRESHOLD=$disk_threshold
ALERT_SOUND=ON
ALERT_LOG=ON
EOF
    
    echo -e "${GREEN}✓ Uyarı ayarları kaydedildi${NC}"
    echo ""
    echo "Ayarlar:"
    echo "  • CPU Eşiği: $cpu_threshold%"
    echo "  • Bellek Eşiği: $mem_threshold%"
    echo "  • Disk Eşiği: $disk_threshold%"
}

################################################################################
# 7. CRON İŞLERİ
################################################################################

setup_cron_jobs() {
    echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║         PEGASUS CRON JOB SCHEDULER                            ║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    
    echo "Otomatik İşlemler:"
    echo "1) Her saatte sistem taraması"
    echo "2) Günlük güvenlik denetimi"
    echo "3) Haftalık performans raporu"
    echo "4) Aylık yedekleme"
    echo "5) Hiçbiri"
    echo ""
    
    read -p "Seçim yapınız (1-5): " cron_choice
    
    case $cron_choice in
        1)
            echo "0 * * * * bash /sdcard/pegasus-monitor.sh > /sdcard/pegasus_cron.log 2>&1" | crontab -
            echo -e "${GREEN}✓ Saatlik tarama ayarlandı${NC}"
            ;;
        2)
            echo "0 2 * * * bash /sdcard/pegasus-monitor.sh --security-audit >> /sdcard/pegasus_cron.log 2>&1" | crontab -
            echo -e "${GREEN}✓ Günlük güvenlik denetimi ayarlandı${NC}"
            ;;
        *)
            echo -e "${YELLOW}Cron işleri atlanmıştır${NC}"
            ;;
    esac
}

################################################################################
# MENÜ
################################################################################

show_advanced_menu() {
    while true; do
        clear
        echo -e "${CYAN}"
        echo "╔════════════════════════════════════════════════════════════════╗"
        echo "║      PEGASUS PROJECT v6.0 - ADVANCED FEATURES MENU            ║"
        echo "╚════════════════════════════════════════════════════════════════╝"
        echo -e "${NC}"
        echo ""
        
        echo -e "${YELLOW}1.${NC} Sistem Taraması"
        echo -e "${YELLOW}2.${NC} Ağ Güvenlik Denetimi"
        echo -e "${YELLOW}3.${NC} Performans Benchmarki"
        echo -e "${YELLOW}4.${NC} Olay Türü Monitörü"
        echo -e "${YELLOW}5.${NC} Veri Dışa Aktarma"
        echo -e "${YELLOW}6.${NC} Uyarı Ayarları"
        echo -e "${YELLOW}7.${NC} Cron İşleri"
        echo -e "${YELLOW}0.${NC} Çıkış"
        echo ""
        
        read -p "Seçim yapınız: " choice
        
        case $choice in
            1)
                advanced_system_scan
                read -p "Enter tuşuna basınız..."
                ;;
            2)
                network_security_audit
                read -p "Enter tuşuna basınız..."
                ;;
            3)
                performance_benchmark
                read -p "Enter tuşuna basınız..."
                ;;
            4)
                event_type_monitor
                read -p "Enter tuşuna basınız..."
                ;;
            5)
                advanced_data_export
                read -p "Enter tuşuna basınız..."
                ;;
            6)
                setup_alerts
                read -p "Enter tuşuna basınız..."
                ;;
            7)
                setup_cron_jobs
                read -p "Enter tuşuna basınız..."
                ;;
            0)
                return
                ;;
            *)
                echo -e "${RED}Geçersiz seçim${NC}"
                sleep 1
                ;;
        esac
    done
}

# Yardımcı fonksiyonlar
get_cpu_info() {
    if [ -f /proc/stat ]; then
        awk '/^cpu / {print int((($2+$3+$4) / ($2+$3+$4+$5)) * 100)}' /proc/stat
    else
        echo "0"
    fi
}

get_memory_info() {
    if [ -f /proc/meminfo ]; then
        awk 'NR==1{total=$2} NR==2{free=$2} END{if(total>0) print int(((total-free)/total)*100); else print "0"}' /proc/meminfo
    else
        echo "0"
    fi
}

get_storage_info() {
    if command -v df &> /dev/null; then
        df /sdcard 2>/dev/null | awk 'NR==2{if(NF>=5) print int($5); else print "0"}'
    else
        echo "0"
    fi
}

get_active_connections() {
    if [ -f /proc/net/tcp ]; then
        awk 'NR>1 {count++} END {print count}' /proc/net/tcp
    else
        echo "0"
    fi
}

get_process_count() {
    if [ -d /proc ]; then
        ls -d /proc/[0-9]* 2>/dev/null | wc -l
    else
        echo "0"
    fi
}

# Ana program
if [ "$1" == "--advanced" ]; then
    show_advanced_menu
else
    show_advanced_menu
fi
